#!/usr/bin/env bash
#
# Export data from a Mongo database

MONGO_USER='marco';
MONGO_PASS='esticazzi!123';
MONGO_DB='web-scraping';
MONGO_URI="mongodb://${MONGO_USER}:${MONGO_PASS}@cluster0.e76px.mongodb.net/${MONGO_DB}";
#MONGO_URI="mongodb://localhost:27017/web-scraping";
MONGO_COLLECTION="$1"

TMP="tmp/mongo/${MONGO_DB}"
OUTPUT_FILE="${TMP}/${MONGO_COLLECTION}.json"

mkdir -p "$TMP"

if [ -z "$MONGO_COLLECTION" ]; then
  echo "Please specify collection to export"; exit -1
fi
if [ -f "$OUTPUT_FILE" ]; then
  echo "Output file $OUTPUT_FILE exists already"; exit -1
fi

/usr/bin/mongoexport --uri="$MONGO_URI" --collection="$MONGO_COLLECTION" --out "$OUTPUT_FILE"
if [ $? -eq 1 ]; then
  rm -rf "$TMP"
fi