#!/usr/bin/env bash
#
# Import data into a Mongo database

MONGO_USER='marco';
MONGO_PASS='esticazzi!123';
MONGO_DB='web-scraping';
MONGO_URI="mongodb://${MONGO_USER}:${MONGO_PASS}@cluster0.e76px.mongodb.net/${MONGO_DB}";

COLLECTION="$1"

if [ -z "$COLLECTION" ]; then
  echo "Please specify collection to import"; exit -1
fi
if [ ! -f "$INPUT_FILE" ]; then
  echo "Input file $INPUT_FILE does not exist"; exit -1
fi

TMP="tmp/mongo/${MONGO_DB}"
INPUT_FILE="${TMP}/${COLLECTION}.json"

/usr/bin/mongoimport --uri "$MONGO_URI" --drop --collection "$COLLECTION" --file "$INPUT_FILE"
if [ $? -eq 1 ]; then
  rm -rf "$TMP"
fi