#!/usr/bin/env bash
#
# Import data into a Mongo database

MONGO_USER='marco';
MONGO_PASS='esticazzi!123';
MONGO_DB='web-scraping';
MONGO_URI="mongodb://${MONGO_USER}:${MONGO_PASS}@cluster0.e76px.mongodb.net/${MONGO_DB}";
MONGO_COLLECTION="$1"

TMP="tmp/mongo/${MONGO_DB}"
INPUT_FILE="${TMP}/${MONGO_COLLECTION}.json"

if [ -z "$MONGO_COLLECTION" ]; then
  echo "Please specify collection to import"; exit -1
fi
if [ ! -f "$INPUT_FILE" ]; then
  echo "Input file does $INPUT_FILE not exist"; exit -1
fi

/usr/bin/mongoimport --uri "$MONGO_URI" --drop --collection "$MONGO_COLLECTION" --file "$INPUT_FILE"
if [ $? -eq 1 ]; then
  rm -rf "$TMP"
fi