#!/usr/bin/env bash
#
# Delete one document by _id from collection

db=${1:-web-scraping}
collection=${2:-items}
id=${3}

if [ -z "$db" ]; then
  echo "Please specify db name as first parameter"; exit -1
fi
if [ -z "$collection" ]; then
  echo "Please specify collection name as second parameter"; exit -1
fi
if [ -z "$id" ]; then
  echo "Please specify an id as third parameter"; exit -1
fi
echo 'db.'$collection'.deleteOne({"_id": ObjectId("'$id'")})' | \
mongo "$db" --quiet | \
grep -v '^bye$'
