#!/usr/bin/env bash
#
# Delete documents from collection

db=${1:-web-scraping}
collection=${2:-items}
filter=${3}

if [ -z "$db" ]; then
  echo "Please specify db name as first parameter"; exit -1
fi
if [ -z "$collection" ]; then
  echo "Please specify collection name as second parameter"; exit -1
fi
if [ -z "$filter" ]; then
  echo "Please specify a filter as third parameter"; exit -1
fi
echo 'db.'$collection'.deleteMany('$filter')' | \
mongo "$db" --quiet | \
grep -v '^bye$'