#!/usr/bin/env bash
#
# Update prop in collection

propName="${1}"
propValue="${2}"
db="${3-web-scraping}"
collection="${4-items.persons}"

echo 'db.'${collection}'.updateMany({provider:"pf"}, {$set: {'$propName':'$propValue'}})' | \
mongo "$db" --quiet | \
grep -v '^bye$'